server:
  port: 8092

spring:
  application:
    name: springboot-feign

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    default-to-properties: true  # 如果在代码中定义了@configuration的values，这里如果是true，则会覆盖代码中的值；

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000