server:
  port: 8092

spring:
  application:
    name: springboot-feign

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


feign:
  hystrix:
    enabled: true  #Feign包裹的的所有方法都会自带断路器(circuit breaker)
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
        loggerLevel: basic
    default-to-properties: false  # 如果在代码中定义了@configuration的values，这里如果是true，则以这里的配置为准；

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000   #缺省为1000