#&allowPublicKeyRetrieval=true作用
#在使用MyBatis的项目中，升级了数据库驱动的版本，在项目启动过程中，抛出了Public Key Retrieval is not allowed异常

spring:
  application:
    name:  springboot_mybatis
  datasource:
    #{serverAddress}可以填服务名或IP
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    continue-on-error: false
    initialization-mode: always
    #以下配置druid连接池
    type: com.alibaba.druid.pool.DruidDataSource   #表明使用Druid数据库连接池
    druid:
      initial-size: 5   #初始化时建立物理连接的个数。
      max-active: 20    #最大连接池数量
      min-idle:  5      #最小连接池数量
      max-wait:  3000   #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: false #是否缓存preparedStatement，也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      max-open-prepared-statements: -1  #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      time-between-eviction-runs-millis: 60000  #配置检测可以关闭的空闲连接间隔时间
      min-evictable-idle-time-millis: 300000    # 配置连接在池中的最小生存时间
      max-evictable-idle-time-millis: 400000
      filters: stat,wall    #监控统计的stat,以及防sql注入的wall
      aop-patterns: com.springboot.mmybatis.controller.*     #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      web-stat-filter:
        url-pattern: /*   #添加过滤规则
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"   #忽略过滤的格式
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: root
        allow: 127.0.0.1
        deny:
mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql

server:
  port: 8096   #可以填入任意值，持续交付过时会被覆盖

logging:
  file: "logs/${spring.application.name}"
debug: true