server:
  port: 9002
spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 192.168.101.118
    port: 5672
    username: admin
    password: admin
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true


